Improved Support for Video Replay Support (including POST request canonicalization)
openzim/warc2zim pull request #83
Opened 2021-10-29 16:58 UTC by ikreymer

- Support video replay for current youtube and vimeo
- Use special iterate that matches request<->response pairs and includes POST request data from cdxj-indexer library.
- Update existing fuzzy matching rules for videos
- Utility: allow loading custom sw.js from a local path as well as URL
- Fixes #80

2021-11-01 16:40 UTC, kelson42 commented
@rgaudin Any feedback?

2021-11-01 23:02 UTC, rgaudin requested changes
Thanks for the PR @ikreymer !

Regarding warc2zim, it looks good to me except for the unpinned webac download in tests. We should definitely use fixed versions.

Unfortunately, the replayer is not working as expected. Here's what I get from [your kiwix-serve](https://kiwix-dev.webrecorder.net)

- Vimeo: video is *full sized* but the cover is blank (white). Playback works fine though.
- Procrastination: Gets proper cover/UI but playback fails to start (although the progress bar appears to be buffering some data)
<img width="654" alt="Screen Shot 2021-11-01 at 23 49 34" src="https://user-images.githubusercontent.com/57929/139752238-548a58cd-46de-4fcb-b0b4-577a17bf4223.png">
- Youtube: same result but it's all in full-size (like Vimeo)
- Monabeach: all videos appear as grey boxes for a **very long time**. Then clicking play brings a black box for another long time.

When using the ZIM files, monabeach has a different behavior:
- Covers loads instantly on Safari
- Only the first three work. The other ones leads to black boxes.
- When clicking play, I can see a flashing kiwix-serve chrome (the toolbar) being displayed in the video box, before it goes dark.

I'd be happy to provide more inputs on something more specific. Maybe we should focus on the single-video tests first and once this works fine, expand to the more complex example

2021-11-02 00:17 UTC, ikreymer commented on tests/test_warc_to_zim.py
> -                "https://cdn.jsdelivr.net/npm/@webrecorder/wabac@2.1.0-dev.3/dist/",
Sure, updated to latest release, just checking for ability to download the file here.

2021-11-02 00:22 UTC, ikreymer commented
Thanks for testing!
Unfortunately, I can't really repro the issues you are seeing. Will see if I can generate better samples, technically, these were created with archiveweb.page extension, not with zimit itself (since didn't have this ready yet).

Could you list the browsers and OS you are using to test? Perhaps there's a codec issue with Linux..

> Unfortunately, the replayer is not working as expected. Here's what I get from [your kiwix-serve](https://kiwix-dev.webrecorder.net)
> 
> * Vimeo: video is _full sized_ but the cover is blank (white). Playback works fine though.

I think that's what it is in this example?

> * Procrastination: Gets proper cover/UI but playback fails to start (although the progress bar appears to be buffering some data)
> 
Unfortunately, I can't repro this error, was able to get it to play in all three browsers but on OS X.

> 
> - Youtube: same result but it's all in full-size (like Vimeo)

Yes, this will be a full page as well as it using the embed directly. Maybe will remove this example.

 - Monabeach: all videos appear as grey boxes for a **very long time**. Then clicking play brings a black box for another long time.

Hmm, perhaps the initial load from this server is slow.

> When using the ZIM files, monabeach has a different behavior:
> 
> * Covers loads instantly on Safari
> * Only the first three work. The other ones leads to black boxes.
> * When clicking play, I can see a flashing kiwix-serve chrome (the toolbar) being displayed in the video box, before it goes dark.
> 

This is correct, only the first 3 videos are captured here (this was done manually again).

> I'd be happy to provide more inputs on something more specific. Maybe we should focus on the single-video tests first and once this works fine, expand to the more complex example

Sure, if you have additional examples, would be good to run some tests with the new zimit branch.
It sounds like main issue is with some of the single page youtube, maybe a capture via browsertrix-crawler would work better..

2021-11-02 00:49 UTC, ikreymer commented
Here's an updated version of youtube: https://kiwix-dev.webrecorder.net/yt-2/
Can you see if this works, either hosted or locally?

2021-11-02 09:08 UTC, rgaudin commented
> Here's an updated version of youtube: https://kiwix-dev.webrecorder.net/yt-2/ Can you see if this works, either hosted or locally?
> 
> Edit: Also added: https://kiwix-dev.webrecorder.net/yt-3/

Both work fine in Chrome and Safari on macOS, including when served via kiwix-serve with network disabled 👍 

I'm unable to get it working on Firefox though. Either I get the same error captured above or a black box…
There doesn't seem to be any error in the console (except a webfont and a favicon). Network tab shows a few (3) mp4 videoplayback chunks…


Ah and I spent a minute complaining about github not working again… forgot to re-enable my network 😅

2021-11-16 10:39 UTC, rgaudin commented
Here's another round of feedback. Not different from earlier though. I am attaching a screencast so it's clearer for everybody.

https://user-images.githubusercontent.com/57929/141967980-fad8cbac-feb9-4d2d-9749-9cda1af61629.mp4

All the tests done on a **cleaned-up** Firefox DE 95.0b7 to make sure there is no cache or previous SW involved. Using DE specifically as FF is my regular browser. I'm testing on macOS Monterey.

Testing from https://kiwix-dev.webrecorder.net/

**yt-2**
- instant cover
- spinner for about 15s
- can see progress bar going a bit (matches with the two 206 requests)
- fails with error message and black video offers
- after a refresh, error stil happens but a lot quicker. About 1-2s

**yt-3**
- quick load of UI
- missing cover (black). This actually seem to vary based on window size. UI is probably trying to switch cover image based on size and we only have the scraper one.

**moab**
- relatively quick to load covers and UI
- video1 works OK
- clicking video2 leads to black box with no UI
- video3 works OK
- video4 to 14 black box

**vimeo**
- video frame is full width (not sure if that's expected ; I guess so)
- cover appears blurry while vimeo UI loads
- vimeo UI appears and cover disappears (white)
- video works OK

Now I am also attaching a screencast with Chrome where yt-2 works fine but the other issues are visible.


https://user-images.githubusercontent.com/57929/141969795-e891b637-7837-47e7-b484-c10ce1f2546c.mp4



@ikreymer could you please test with a **fresh** browser?

2021-12-09 04:31 UTC, ikreymer commented
@rgaudin Thank you for the detailed videos, and sorry for late response.

The videos 4-14 on moab are not expected to work, they were never archived (this was a manual test). Sorry for the confusion!

I have the same results on chrome and I think everything is working as expected on chrome.

The only issues I see are on firefox:
- yt-2 should work. For me, it does, tried with fresh firefox
- the first 3 videos on moab should work.
- the loading of moab videos is very slow on firefox, perhaps the loading issue is related to that. I will see if I can track that down.

2021-12-09 09:44 UTC, rgaudin commented
Thanks for the feedback ; looking forward to hear your findings. Ping me if there's anything I can do to help/test.

2021-12-13 22:59 UTC, ikreymer commented
Unfortunately, it seems like there are some existing bugs with the Firefox service worker implementations, which results in requests just hanging and/or failing with `NS_BINDING_ABORTED` errors. I'm not quite sure when it happens, perhaps when there's a delay in responding, because it has to load from the upstream server. I've noticed that the requests that 'hang' are those that are duplicated (same URL loaded from multiple iframes), so maybe Firefox is getting confused by fetching same URL from upstream server.. not entirely sure. There are some related Firefox bugs such as:
https://bugzilla.mozilla.org/show_bug.cgi?id=1673534 which have suggested workaround to uninstall the service workers, which of course we can't do. The logging for firefox service worker is also a bit limited (https://bugzilla.mozilla.org/show_bug.cgi?id=1506892)

The problem seemed to be improved by enabling cacheing, so that multiple requests to the same `A/<url>` are cached and not fetched again. This seems to improve the replay in Firefox - the issues may still happen on first load, but after refresh, the pages do load and play for the examples below.

You can try this out in:
https://kiwix-dev.webrecorder.net/moab_2021-12/A/manonabeach.com/
and
https://kiwix-dev.webrecorder.net/yt-2_2021-12/

(be sure to clear cache and service workers or try new profile)

It still seems like there are issues with Firefox service workers, which is very hard to pinpoint, but this should be a bit better. (The cacheing is also similar to how loading from WACZ works, which does not have these issues).

2021-12-14 13:45 UTC, rgaudin commented
Thank you for the reseach @ikreymer.

I can confirm that on moab, videos 1-3 works reliably. The cover/UI takes forever to loads though and , indeed, load instantly upon refresh.

On yt-2, there's no luck. It's still the same exact behavior.

You last comment regarding WACZ is unclear. Do you mean that WACZ works in the same way the ZIM now works (ie, better after a refresh) because of how content is served or do you mean that with WACZ, those videos works reliably on FF ?

2022-01-04 09:15 UTC, rgaudin commented
@ikreymer ? Any answer for that last question ?

2022-01-05 05:32 UTC, ikreymer commented
> On yt-2, there's no luck. It's still the same exact behavior.
> 

Hm, very odd, I'm unable to reproduce the issue, works on FF all versions for me.. Only thing I can think of is some sort of locale related difference..

> You last comment regarding WACZ is unclear. Do you mean that WACZ works in the same way the ZIM now works (ie, better after a refresh) because of how content is served or do you mean that with WACZ, those videos works reliably on FF ?

The second one. I meant that it seems to load reliably in FF from WACZ, and I suspect that is because the WACZ loading always caches to indexeddb, so avoids duplicate requests.

I think this might be as good as this can get for now.. Or do you want to try running additional tests with zimit of pages with youtube / vimeo?

2022-01-05 09:55 UTC, rgaudin commented
Thanks ; our understanding also ; wanted to be sure about this WACZ difference but we'll merge and use this for now.

2022-01-05 11:41 UTC, rgaudin approved these changes

2022-01-05 11:41 UTC, merged